language: generic
os: linux
dist: xenial
services:
  - docker

before_install:
  - docker build -t nscnm87/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nscnm87/docker-react npm run test